# Generated by Django 6.0.6 on 2026-06-09 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.URLField(default='https://via.placeholder.com/250'),
            preserve_default=False,
        ),
    ]
